const constants = {
  ATTRIBUTES_RECEIVED: 'ATTRIBUTES_RECEIVED',
  ATTRIBUTE_CREATED: 'ATTRIBUTE_CREATED',
  ATTRIBUTE_UPDATED: 'ATTRIBUTE_UPDATED',
  ATTRIBUTE_DELETED: 'ATTRIBUTE_DELETED',

  VALUES_RECEIVED: 'VALUES_RECEIVED',
  VALUE_CREATED: 'VALUE_CREATED',
  VALUE_UPDATED: 'VALUE_UPDATED',
  VALUE_DELETED: 'VALUE_DELETED'
}

export default constants