const constants = {
  ATTRIBUTES_RECEIVED: 'ATTRIBUTES_RECEIVED',
  ATTRIBUTE_CREATED: 'ATTRIBUTE_CREATED',
  ATTRIBUTE_UPDATED: 'ATTRIBUTE_UPDATED',
  ATTRIBUTE_DELETED: 'ATTRIBUTE_DELETED',
  ATTRIBUTES_FILTERED: 'ATTRIBUTES_FILTERED',
  
  SET_ATTRIBUTE_PARAMS: 'SET_ATTRIBUTE_PARAMS'
}

export default constants